# =====================================================================
# gen_py_dpi_files.tcl
# Generates C DPI socket transport files (protocol.h, socket_transport.h, socket_transport.c, dpi_socket.c)
# =====================================================================

proc generate_py_dpi_files {project_name ref_dir} {
    set proj_upper [string toupper $project_name]
    set dpi_dir "${ref_dir}/dpi"
    if {![file exists $dpi_dir]} {
        file mkdir $dpi_dir
    }

    # 1. protocol.h
    set h_file "${dpi_dir}/protocol.h"
    set h_content ""
    append h_content "#ifndef PROTOCOL_H\n"
    append h_content "#define PROTOCOL_H\n\n"
    append h_content "#include <stdint.h>\n\n"
    append h_content "/************************************************************\n"
    append h_content " * Protocol Information\n"
    append h_content " ************************************************************/\n"
    append h_content "#define PROTOCOL_VERSION      1\n\n"
    append h_content "/************************************************************\n"
    append h_content " * Message Types\n"
    append h_content " ************************************************************/\n"
    append h_content "typedef enum\n"
    append h_content "{\n"
    append h_content "    MSG_${proj_upper}_REQUEST  = 1,\n"
    append h_content "    MSG_${proj_upper}_RESPONSE = 2,\n\n"
    append h_content "    MSG_PING         = 3,\n"
    append h_content "    MSG_PONG         = 4,\n\n"
    append h_content "    MSG_SHUTDOWN     = 5\n\n"
    append h_content "} message_type_t;\n\n"
    append h_content "/************************************************************\n"
    append h_content " * Packet Constants\n"
    append h_content " ************************************************************/\n"
    append h_content "#define HEADER_SIZE       8\n"
    append h_content "#define MAX_PAYLOAD_SIZE  1024\n\n"
    append h_content "/************************************************************\n"
    append h_content " * Packet Header\n"
    append h_content " ************************************************************/\n"
    append h_content "typedef struct\n"
    append h_content "{\n"
    append h_content "    uint8_t  version;\n"
    append h_content "    uint8_t  msg_type;\n"
    append h_content "    uint16_t payload_length;\n"
    append h_content "    uint32_t transaction_id;\n\n"
    append h_content "} packet_header_t;\n\n"
    append h_content "#endif\n"

    set fp [open $h_file w]; puts -nonewline $fp $h_content; close $fp
    puts "Python DPI Protocol Header generated: $h_file"

    # 2. socket_transport.h
    set sock_h_file "${dpi_dir}/socket_transport.h"
    set sock_h_content ""
    append sock_h_content "#ifndef SOCKET_TRANSPORT_H\n"
    append sock_h_content "#define SOCKET_TRANSPORT_H\n\n"
    append sock_h_content "#include <stdint.h>\n\n"
    append sock_h_content "/************************************************************\n"
    append sock_h_content " * Socket Configuration\n"
    append sock_h_content " ************************************************************/\n"
    append sock_h_content "#define SERVER_IP     \"127.0.0.1\"\n"
    append sock_h_content "#define SERVER_PORT   5000\n\n"
    append sock_h_content "/************************************************************\n"
    append sock_h_content " * API\n"
    append sock_h_content " ************************************************************/\n"
    append sock_h_content "int socket_connect(void);\n\n"
    append sock_h_content "int socket_disconnect(void);\n\n"
    append sock_h_content "int socket_send(unsigned char *buffer, int size);\n\n"
    append sock_h_content "int socket_receive(unsigned char *buffer);\n\n"
    append sock_h_content "#endif\n"

    set fp [open $sock_h_file w]; puts -nonewline $fp $sock_h_content; close $fp
    puts "Python DPI Socket Transport Header generated: $sock_h_file"

    # 3. socket_transport.c
    set sock_c_file "${dpi_dir}/socket_transport.c"
    set sock_c_content ""
    append sock_c_content "#include \"socket_transport.h\"\n"
    append sock_c_content "#include \"protocol.h\"\n\n"
    append sock_c_content "#include <stdio.h>\n"
    append sock_c_content "#include <string.h>\n\n"
    append sock_c_content "#ifdef _WIN32\n\n"
    append sock_c_content "#include <winsock2.h>\n\n"
    append sock_c_content "#pragma comment(lib, \"ws2_32.lib\")\n\n"
    append sock_c_content "static SOCKET socket_fd = INVALID_SOCKET;\n\n"
    append sock_c_content "#else\n\n"
    append sock_c_content "#include <unistd.h>\n"
    append sock_c_content "#include <arpa/inet.h>\n"
    append sock_c_content "#include <sys/socket.h>\n\n"
    append sock_c_content "static int socket_fd = -1;\n\n"
    append sock_c_content "#endif\n\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "// Connect\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "int socket_connect(void)\n"
    append sock_c_content "{\n"
    append sock_c_content "#ifdef _WIN32\n"
    append sock_c_content "    WSADATA wsa;\n"
    append sock_c_content "    WSAStartup(MAKEWORD(2,2), &wsa);\n"
    append sock_c_content "#endif\n\n"
    append sock_c_content "    struct sockaddr_in server_addr;\n"
    append sock_c_content "    socket_fd = socket(AF_INET, SOCK_STREAM, 0);\n"
    append sock_c_content "    if(socket_fd < 0) {\n"
    append sock_c_content "        return -1;\n"
    append sock_c_content "    }\n\n"
    append sock_c_content "    memset(&server_addr, 0, sizeof(server_addr));\n"
    append sock_c_content "    server_addr.sin_family = AF_INET;\n"
    append sock_c_content "    server_addr.sin_port   = htons(SERVER_PORT);\n"
    append sock_c_content "    server_addr.sin_addr.s_addr = inet_addr(SERVER_IP);\n\n"
    append sock_c_content "    if(connect(socket_fd, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0) {\n"
    append sock_c_content "        return -1;\n"
    append sock_c_content "    }\n"
    append sock_c_content "    return 0;\n"
    append sock_c_content "}\n\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "// Disconnect\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "int socket_disconnect(void)\n"
    append sock_c_content "{\n"
    append sock_c_content "#ifdef _WIN32\n"
    append sock_c_content "    closesocket(socket_fd);\n"
    append sock_c_content "    WSACleanup();\n"
    append sock_c_content "#else\n"
    append sock_c_content "    close(socket_fd);\n"
    append sock_c_content "#endif\n"
    append sock_c_content "    return 0;\n"
    append sock_c_content "}\n\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "// Send Packet\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "int socket_send(unsigned char *buffer, int size)\n"
    append sock_c_content "{\n"
    append sock_c_content "    return send(socket_fd, (char *)buffer, size, 0);\n"
    append sock_c_content "}\n\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "// Receive Packet\n"
    append sock_c_content "//------------------------------------------------------------\n"
    append sock_c_content "int socket_receive(unsigned char *buffer)\n"
    append sock_c_content "{\n"
    append sock_c_content "    int received;\n"
    append sock_c_content "    // Receive Header\n"
    append sock_c_content "    received = recv(socket_fd, (char *)buffer, HEADER_SIZE, 0);\n"
    append sock_c_content "    if(received <= 0) {\n"
    append sock_c_content "        return -1;\n"
    append sock_c_content "    }\n\n"
    append sock_c_content "    // Payload Length\n"
    append sock_c_content "    uint16_t payload_length;\n"
    append sock_c_content "    payload_length = ((uint16_t)buffer\[2\] << 8) | (uint16_t)buffer\[3\];\n\n"
    append sock_c_content "    // Receive Payload\n"
    append sock_c_content "    received = recv(socket_fd, (char *)(buffer + HEADER_SIZE), payload_length, 0);\n"
    append sock_c_content "    if(received <= 0) {\n"
    append sock_c_content "        return -1;\n"
    append sock_c_content "    }\n"
    append sock_c_content "    return HEADER_SIZE + payload_length;\n"
    append sock_c_content "}\n"

    set fp [open $sock_c_file w]; puts -nonewline $fp $sock_c_content; close $fp
    puts "Python DPI Socket Transport Source generated: $sock_c_file"

    # 4. dpi_socket.c
    set dpi_c_file "${dpi_dir}/dpi_socket.c"
    set dpi_c_content ""
    append dpi_c_content "#include \"svdpi.h\"\n"
    append dpi_c_content "#include \"socket_transport.h\"\n\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "// Connect\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "int rm_connect()\n"
    append dpi_c_content "{\n"
    append dpi_c_content "    return socket_connect();\n"
    append dpi_c_content "}\n\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "// Disconnect\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "int rm_disconnect()\n"
    append dpi_c_content "{\n"
    append dpi_c_content "    return socket_disconnect();\n"
    append dpi_c_content "}\n\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "// Send Packet\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "int rm_send(const unsigned char *packet, int size)\n"
    append dpi_c_content "{\n"
    append dpi_c_content "    return socket_send((unsigned char *)packet, size);\n"
    append dpi_c_content "}\n\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "// Receive Packet\n"
    append dpi_c_content "//------------------------------------------------------------\n"
    append dpi_c_content "int rm_receive(unsigned char *packet)\n"
    append dpi_c_content "{\n"
    append dpi_c_content "    return socket_receive(packet);\n"
    append dpi_c_content "}\n"

    set fp [open $dpi_c_file w]; puts -nonewline $fp $dpi_c_content; close $fp
    puts "Python DPI Bridge C Source generated: $dpi_c_file"
}
