import json
import os
from pathlib import Path

def load_rag_chunks(category: str) -> list[str]:
    """
    Load styling and formatting chunks deterministically based on the task category.
    This replaces semantic search with simple category filtering.
    """
    rag_file = Path(__file__).parent / "rag_chunks.json"
    if not rag_file.exists():
        return []
        
    try:
        with open(rag_file, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        chunks = data.get(category, [])
        return [f"**{chunk['topic']}**\n{chunk['content']}" for chunk in chunks]
    except Exception as e:
        print(f"Error loading RAG chunks: {e}")
        return []

def read_file_safely(filepath: str) -> str:
    """Read a file safely and return its content."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        return f"// Error reading file {filepath}: {e}"

def build_task_prompt(
    task_category: str,
    target_skeleton_file: str,
    project_context_files: list[str],
    user_instructions: str = "",
    ref_doc_file: str = None,
) -> str:
    """
    Builds the complete prompt for the external LLM based on the RAG architecture.
    
    Args:
        task_category: "assertions", "coverage", "random_constraints",
                       "reference_model_sv", "reference_model_c", "reference_model_py"
        target_skeleton_file: Path to the file generated by the tool that needs AI completion.
        project_context_files: List of paths to existing files (RTL, Interfaces, etc.)
        user_instructions: Optional specific instructions from the user.
        ref_doc_file: Optional path to a language-specific style reference file (for reference models)
    """
    # ── Determine output language from category ───────────────────────────────
    is_ref_model = task_category.startswith("reference_model_")
    if task_category == "reference_model_c":
        output_lang = "C"
        output_ext  = ".c"
        lang_label  = "C"
        code_fence  = "c"
    elif task_category == "reference_model_py":
        output_lang = "Python"
        output_ext  = ".py"
        lang_label  = "Python"
        code_fence  = "python"
    else:
        output_lang = "SystemVerilog"
        output_ext  = ".sv"
        lang_label  = "SystemVerilog"
        code_fence  = "systemverilog"

    # ── 1. Style / Format Reference section ──────────────────────────────────
    if is_ref_model and ref_doc_file and os.path.exists(ref_doc_file):
        doc_content = read_file_safely(ref_doc_file)
        style_section = (
            f"**Reference Model Style Example ({lang_label})**\n"
            f"Study the following example carefully. Match its structure and naming conventions exactly.\n\n"
            f"```{code_fence}\n{doc_content}\n```"
        )
    else:
        style_chunks = load_rag_chunks(task_category)
        style_section = "\n\n---\n\n".join(style_chunks) if style_chunks else "No specific style rules found."

    # ── 2. Design Context / Project Files ────────────────────────────────────
    context_section = ""
    for file_path in project_context_files:
        if not os.path.exists(file_path): continue
        filename = os.path.basename(file_path)
        content  = read_file_safely(file_path)
        ext = os.path.splitext(filename)[1].lower()
        fence = "c" if ext in (".c", ".h") else "python" if ext == ".py" else "systemverilog"
        context_section += f"--- File: {filename} ---\n```{fence}\n{content}\n```\n\n"

    if not context_section:
        context_section = "No project context files provided."

    # ── 3. Target Skeleton File ───────────────────────────────────────────────
    skeleton_content = "No skeleton provided."
    if target_skeleton_file and os.path.exists(target_skeleton_file):
        skeleton_content = read_file_safely(target_skeleton_file)

    base_instruction = (
        f"Generate the complete {task_category.replace('_', ' ').title()} implementation "
        f"by filling the provided skeleton file."
    )
    
    if user_instructions.strip():
        user_instructions = f"{base_instruction}\n\nUSER SPECIFIC INSTRUCTIONS:\n{user_instructions}"
    else:
        user_instructions = base_instruction

    # ── 4. Build output constraints per language ──────────────────────────────
    if output_lang == "C":
        output_constraint = (
            "- Do NOT include any markdown fences (no ```), no explanations outside the code\n"
            "- START your response with the VERY FIRST LINE of code (#include / typedef / void ...) — NO sentence before it\n"
            "- Do NOT write any sentence after the last closing brace\n"
            "- The output must be a complete, directly-usable .c file\n"
            "- Match the formatting style from Section 1 exactly\n"
            "- STRICT REQUIREMENT: The code must be 100% syntactically correct C99/C11"
        )
    elif output_lang == "Python":
        output_constraint = (
            "- Do NOT include any markdown fences (no ```), no explanations outside the code\n"
            "- START your response with the VERY FIRST LINE of code (import / def / class ...) — NO sentence before it\n"
            "- Do NOT write any sentence after the last line of the module\n"
            "- The output must be a complete, directly-usable .py file\n"
            "- Match the formatting style from Section 1 exactly\n"
            "- STRICT REQUIREMENT: The code must be 100% syntactically correct Python 3"
        )
    else:  # SystemVerilog
        output_constraint = (
            "- Do NOT include any markdown fences (no ```), no explanations, no prose outside the code\n"
            "- START your response with the VERY FIRST LINE of code (module / class / interface / package ...) — NO sentence before it\n"
            "- Do NOT write any explanation, comment, or sentence after the closing endclass/endmodule\n"
            f"- The output must be a complete, directly-usable {output_ext} file containing the filled skeleton\n"
            "- Match the formatting style from Section 1 exactly\n"
            "- STRICT REQUIREMENT: The code MUST be 100% syntactically correct and comply fully with the IEEE 1800 SystemVerilog standard.\n"
            "- Act as a strict SystemVerilog linter internally before generating the text."
        )

    # ── SECTION 0: Tool Architecture (injected in EVERY prompt) ──────────────
    tool_architecture_section = """
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
SECTION 0 \u2014 TOOL ARCHITECTURE  \u26a0 READ THIS FIRST \u2014 NON-NEGOTIABLE \u26a0
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550

This is a UVM verification tool that operates on a STRICT CYCLE-BY-CYCLE basis.
Understanding this architecture is MANDATORY before writing any code.

+---------------------------------------------------------------------+
|                 CYCLE-BY-CYCLE DATA FLOW (every clock edge)         |
|                                                                     |
|  Sequence  --randomize()-->  seq_item  --drive()-->  DUT           |
|                                                           |         |
|  Monitor <-------------- captures ALL signals <----------+         |
|     |                      (inputs + outputs)                       |
|     +-> Scoreboard / Predictor  (compares DUT vs Reference Model)  |
|     +-> Coverage Collector      (samples covergroup every cycle)    |
+---------------------------------------------------------------------+

KEY FACTS -- every one of these is critical for your code:

  [FACT 1] The Driver sends a NEW seq_item to the DUT on EVERY single clock
           cycle -- regardless of what the DUT is doing (IDLE, BUSY, or RESET).

  [FACT 2] The Monitor captures ALL interface signals (inputs AND outputs)
           on EVERY single clock cycle and packages them into one seq_item.

  [FACT 3] The Reference Model execute() function is called ONCE per cycle,
           on every cycle. It must produce the correct outputs for that exact cycle.

  [FACT 4] The Coverage Collector calls sample() ONCE per cycle.
           The seq_item it receives contains BOTH inputs and outputs for that cycle.

  [FACT 5] The clock signal is NOT a field in the seq_item. It is used only
           for clocking. Find its exact name in the interface file (Section 3).

  [FACT 6] "Transactions" do not exist here. One cycle = one interaction.
           A UART frame of 11 bits = 11 separate seq_items, one per bit cycle.

  [FACT 7] For sequential DUTs, the model must remember state between cycles.
           If the DUT uses a clock divider (e.g., baud-rate counter), your model
           MUST implement an identical counter to know when to advance state.
"""

    # ── 5. Reference Model Critical Rules ─────────────────────────────────────
    ref_model_rules = ""
    if is_ref_model:
        ref_model_rules = """
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
SECTION 5 \u2014 REFERENCE MODEL CRITICAL RULES  \u26a0 READ BEFORE WRITING \u26a0
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550

RULE 1 \u2014 OUTPUT COMPLETENESS  [Most Common AI Mistake]
Every single output field in the response/struct MUST be explicitly assigned.
Unassigned fields default to ZERO and cause ALL scoreboard comparisons to FAIL.
  \u2717 WRONG: forgot to write  ->  response.tx_out = ...
  \u2713 RIGHT: response.tx_out  = current_tx_bit;
           response.busy    = (state != IDLE);

RULE 2 \u2014 NO DEAD CODE
Every variable you declare and compute MUST be assigned to the final response.
If you compute a value (e.g. parity), you MUST route it to response at the right cycle.
  \u2717 WRONG: parity_val = ^data_reg;           // computed but never used
  \u2713 RIGHT: parity_val = ^data_reg;
           response.tx_out = parity_val;     // used in PARITY state

RULE 3 \u2014 PASS-THROUGH FUNCTIONAL INPUT SIGNALS ONLY
Copy inputs that carry DATA or CONTROL information to the response so the
scoreboard can log them alongside the outputs:
  response.<data_signal>    = request.<data_signal>;
  response.<control_signal> = request.<control_signal>;

DO NOT copy: clk, rst_n (or any reset), or any signal that the FSM already
handles structurally. Copying reset into response causes silent scoreboard mismatches.
  \u2717 WRONG: response.rst_n = request.rst_n;   // reset is structural \u2014 never copy
  \u2713 RIGHT:  response.data_in = request.data_in;  // data bus \u2014 copy this
            response.valid   = request.valid;      // control \u2014 copy this

RULE 4 \u2014 IDENTIFY DUT TYPE FIRST (before writing any code)
Read the RTL in Section 3 carefully and decide:

  (A) COMBINATIONAL DUT - output depends ONLY on current inputs.
      Examples: ALU, Adder, Mux, Decoder, Encoder, CRC logic.
      Action: simple if/case logic, no class-level state needed.

  (B) SIMPLE SEQUENTIAL DUT - output depends on HISTORY but no sub-cycle timing.
      Examples: Simple FSM, basic counter, shift register.
      Action: class-level state registers + FSM that advances every execute() call.

  (C) CLOCKED SEQUENTIAL DUT WITH CLOCK DIVIDER \u2014 \u26a0 MOST COMMON MISTAKE \u26a0
      Examples: UART (baud rate counter), SPI (SCK divider), I2C (timing counter),
                PWM generator, any module where a sub-counter controls state advance.
      The RTL has a sub-counter that counts N cycles before the FSM advances.
      Action: MANDATORY -- implement the clock divider counter. See RULE 8.

  (D) MEMORY / BUFFER DUT - output depends on stored data history.
      Examples: FIFO, RAM, Register File, Line Buffer, History Buffer.
      Action: class-level array/queue as storage + read/write pointer management.

  (E) PIPELINE DUT - multiple stages, output is a delayed version of input.
      Examples: Multi-stage FIR filter, pipelined ALU, streaming FFT stage.
      Action: class-level shift register of values (one entry per pipeline stage).

RULE 5 \u2014 FOR SEQUENTIAL DUTs: MANDATORY STATE MACHINE
If the DUT is sequential (shift register, counter, FIFO, serial protocol, FSM):
  - Declare class-level properties (registers) to hold state between execute() calls.
  - Implement a State Machine with states matching the RTL exactly.
  - The execute() function updates these registers AND outputs on every call.
  \u2717 WRONG: stateless function -- output computed from input only, no memory.
  \u2713 RIGHT: class-level: state, bit_counter, shift_reg, parity_bit, ...
           execute() reads state -> computes output -> transitions to next state.

RULE 6 \u2014 CYCLE-ACCURATE BEHAVIOR IS MANDATORY
The scoreboard compares model output vs RTL output on EVERY single clock cycle.
Your model MUST produce the EXACT same output as the RTL on every cycle.
Trace the RTL state machine in Section 3 cycle-by-cycle and mirror it exactly.

RULE 7 \u2014 PROTOCOL SERIALIZATION CHECKLIST
If the DUT serializes or deserializes data (UART, SPI, I2C, etc.), verify:
  [ ] START bit generated correctly  (check polarity from RTL)
  [ ] Data bits sent LSB-first or MSB-first  (check RTL shift direction)
  [ ] PARITY bit computed AND output in its correct cycle  (not dead code)
  [ ] STOP bit generated correctly
  [ ] busy/valid signal asserted during transfer, deasserted at IDLE
  [ ] Bit counter increments exactly as in RTL
  [ ] Clock divider / baud-rate counter matches RTL (see RULE 8 below)

RULE 8 \u2014 CLOCK DIVIDER / BAUD-RATE COUNTER PATTERN  \u26a0 CRITICAL \u26a0
If the RTL has a clock divider (a sub-counter that must reach N before FSM advances):

  STEP 1: Find the sub-counter in RTL. It looks like:
            always_ff @(posedge clk)
              if (baud_counter == BAUD_DIV-1) baud_counter <= 0;
              else                            baud_counter <= baud_counter + 1;

  STEP 2: Declare it as a class-level register (initialized to 0):
            int unsigned baud_counter;
            localparam   BAUD_DIV = <value from RTL parameters>;

  STEP 3: In execute(), run the divider logic FIRST, before FSM logic:
            // -- Clock divider --
            if (baud_counter < BAUD_DIV - 1) begin
                baud_counter = baud_counter + 1;
                // Hold current output -- do NOT advance FSM
                response.tx_out = last_tx_out;   // hold last driven value
                response.busy   = last_busy;
                return response;
            end
            baud_counter = 0;  // counter reached limit -- now run FSM

  STEP 4: After baud_counter resets, run the FSM case statement.

  \u2717 WRONG: advancing FSM state on every execute() call when RTL has a divider.
  \u2713 RIGHT: FSM only advances when baud_counter == BAUD_DIV-1.
  NOTE: You MUST also track last_tx_out and last_busy as class-level registers
        so the "hold" phase returns the correct held output values.

RULE 9 \u2014 NEVER INCLUDE CLOCK IN THE MODEL  \u26a0 CRITICAL \u26a0
The clock signal is NEVER a field in the seq_item. Do NOT:
  - Accept clk as a parameter to execute()
  - Assign response.clk = request.clk
  - Reference clk in any computation
The clock is used ONLY by UVM infrastructure for timing -- not in the model.

RULE 10 \u2014 COMBINATIONAL vs REGISTERED OUTPUT ASSIGNMENT  \u26a0 CRITICAL \u26a0
Understand WHEN to use current inputs vs stored state for output assignment:

  COMBINATIONAL outputs (assigned by assign/always_comb in RTL):
    -> Assign directly from current request fields (inputs this cycle).
    -> Example: response.full = (depth_counter == MAX_DEPTH);
                (depth_counter is a class-level register, updated this cycle)

  REGISTERED outputs (assigned by always_ff in RTL):
    -> Assign from class-level state registers that were SET IN A PREVIOUS CYCLE.
    -> Example: response.data_out = data_memory[rd_ptr];
                (rd_ptr was updated last cycle; data_out reflects last cycle state)

  HOW TO TELL: Search for the output signal name in RTL.
    Found inside always_ff?  -> use class-level state set by PREVIOUS cycle.
    Found in assign?         -> compute inline from current inputs/state.
"""

    # ── 5b. Assertions Critical Rules ─────────────────────────────────────────
    assertions_rules = ""
    if task_category == "assertions":
        assertions_rules = """
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
SECTION 5 \u2014 ASSERTIONS CRITICAL RULES  \u26a0 READ BEFORE WRITING \u26a0
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550

RULE 1 \u2014 ANALYZE THE RTL BEFORE WRITING ANY PROPERTY
Read the RTL in Section 3 completely. For every output signal, identify:
  (a) Is it registered (always_ff) or combinational (assign/always_comb)?
  (b) What is its reset value?
  (c) What conditions change it?
  (d) Are there forbidden / illegal states?
Never write assertions based on assumptions -- derive them from the actual RTL.

RULE 2 \u2014 COVER EVERY OUTPUT SIGNAL
Write at least one assertion for EVERY output signal in the RTL port list.
Missing outputs = unchecked bugs that will reach silicon.
  [ ] For each output: at least one property that verifies its correct value.
  [ ] Reset assertion: ALL outputs must go to their reset values on rst.
  [ ] Do NOT only write flag/control assertions -- also check data signals.

RULE 3 \u2014 CHOOSE |-> vs |=> CORRECTLY (Critical -- wrong choice = useless assertion)
  |-> is OVERLAPPING implication: consequent is sampled on the SAME clock tick
  as the antecedent. |=> is NON-OVERLAPPING implication: consequent is sampled
  on the NEXT clock tick. Never describe these operators the other way around.

  Use |-> (overlapping, SAME sampled cycle) when:
    - The output is COMBINATIONAL: driven by assign or always_comb in RTL.
    - Example: assign full = (count == MAX); -> check with |->
  Use |=> (non-overlapping, NEXT sampled cycle) when:
    - The output is REGISTERED: driven by always_ff @(posedge clk) in RTL.
    - Example: always_ff count <= count+1; -> check with |=>
  HOW TO DECIDE: derive the sampled timing from the RTL, including nonblocking
  assignments and any enable/latency. Search for the signal in the RTL.
    Found inside always_ff? -> use |=>
    Found in assign or always_comb? -> use |->

RULE 4 \u2014 RESET, FLUSH, AND ACCESSIBILITY
Every property (except the reset check itself) must include a disable iff using
the ACTUAL reset polarity and only real invalidating controls, for example:
    disable iff (!`DUT.<active_low_rst> || `DUT.<real_flush>)
Missing disable iff causes false assertion failures during reset and flush.
Do NOT invent a flush/clear signal. Do NOT use the literal hierarchy "Design";
preserve and use the skeleton's `DUT macro/hierarchy. Reference an internal RTL
signal only when it is demonstrably reachable through that hierarchy or an
existing bind. Otherwise assert the same observable port-level behavior.

RULE 5 \u2014 FOR SEQUENTIAL / PROTOCOL DUTs: USE ## AND EDGE DETECTION
If the DUT is a protocol (UART, SPI, I2C) or has an FSM:
  - Use ## to express timing relationships across multiple cycles.
  - Use $rose() and $fell() to detect signal edges (start bits, handshakes, done pulses).
  - Use $past(signal, N) to reference values from N cycles ago.
  - Use $stable() to verify data integrity around clock edges.
  \u2717 WRONG: only writing same-cycle assertions for a UART TX.
  \u2713 RIGHT: $fell(tx_line) |=> busy, bit_counter==N |-> correct bit in shift_reg.

RULE 6 \u2014 DATA PATH INTEGRITY IS MANDATORY
Do NOT only write control-signal assertions (flags, enables, busy).
You MUST also write assertions that verify the CORRECTNESS of data values:
  - ALU: result == op_a + op_b (or the correct operation)
  - UART: tx_out == shift_reg[bit_counter] in the DATA state
  - FIFO: data_out after pop == data that was pushed (use $past)
  - Pipeline: output == $past(input, N) for N-stage delay

RULE 7 \u2014 EVERY ASSERT MUST HAVE A MEANINGFUL $error MESSAGE
The $error string must identify WHAT failed and IN WHAT CONDITION, e.g.:
  \u2717 WRONG: $error("assertion failed")
  \u2713 RIGHT: $error("full_flag not asserted when count == MAX_DEPTH")
  \u2713 RIGHT: $error("TX bit 0 does not match shift_reg[0] in DATA state")

RULE 8 \u2014 ASSERTION COVERAGE COMPLETENESS CHECKLIST
Before submitting, verify that you have written assertions for:
  [ ] Reset behavior     -- all outputs at reset values after rst asserted
  [ ] Normal operation   -- correct output for each valid input combination
  [ ] Boundary conditions -- behavior at min/max values, full/empty states
  [ ] Protocol timing    -- start/stop bits, bit ordering, handshake timing (if applicable)
  [ ] Data correctness   -- output data values match expected computed values
  [ ] Mutual exclusion   -- pairs of signals that must never be simultaneously active
  [ ] Forbidden states   -- conditions that must never occur (e.g. push when full)

RULE 9 \u2014 CLOCK SIGNAL IDENTIFICATION  \u26a0 CRITICAL \u26a0
The clock signal name MUST be read from the interface/RTL context in Section 2.
  STEP 1: Open the interface file from Section 3 (the .sv file with "interface" keyword).
  STEP 2: Find the port declared as input logic <name> or input wire <name>
          at or near the top -- this is the clock signal.
  STEP 3: Use `DUT.<clock_name> in ALL @(posedge ...) clock expressions.
  \u2717 WRONG: @(posedge `DUT.clk)  when the interface uses USER_CLK or sys_clk
  \u2713 RIGHT: check the exact name from the interface file and use it consistently
           in every property's @(posedge `DUT.<actual_clock_name>).

RULE 10 \u2014 CLOCK DIVIDER / BAUD-RATE ASSERTIONS  \u26a0 CRITICAL \u26a0
If the RTL has a clock divider (a sub-counter before FSM advances):
  - DO NOT assert that FSM state or outputs change every clock cycle -- they won't.
  - DO assert that outputs are STABLE (held constant) during the divider phase.
  - DO assert that the FSM state advances only AFTER the divider completes.

  Example -- UART with baud divider: tx_out should be stable between bit transitions:
    property tx_stable_during_baud;
    @(posedge `DUT.<clk>) disable iff(!`DUT.<rst_n>)
      (`DUT.busy && $stable(`DUT.state))
      |=> $stable(Design.tx_out);
    endproperty

  \u2717 WRONG: asserting tx_out changes every clock cycle for a baud-rate-divided UART.
  \u2713 RIGHT: assert tx_out is STABLE while baud_counter has not yet reached BAUD_DIV.
"""

    # ── 5c. Coverage Critical Rules ──────────────────────────────────────────
    coverage_rules = ""
    if task_category == "coverage":
        coverage_rules = """
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
SECTION 5 \u2014 COVERAGE CRITICAL RULES  \u26a0 READ BEFORE WRITING \u26a0
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550

RULE 1 \u2014 MANDATORY COVERGROUP DECLARATION
You MUST declare a covergroup inside the class, outside of any functions.
It must contain:
  option.per_instance = 1;
  option.goal = 100;
Without this, the coverage collector will not compile or work correctly.

RULE 2 \u2014 COVER ALL INPUTS AND KEY OUTPUTS
Read the RTL in Section 3 and identify every input signal and status flag.
You MUST create a coverpoint for EVERY input and key status output.
Leaving signals uncovered creates coverage holes.

RULE 3 \u2014 RANGE BINS FOR WIDE SIGNALS
Do NOT enumerate every single value for signals wider than 4 bits.
Use range bins (e.g., zero, low, mid, high, max) to split the space meaningfully.
  \u2717 WRONG (for 32-bit): bins val_1 = {1}; bins val_2 = {2}; ... (impossible)
  \u2713 RIGHT (for 32-bit): bins low = {[1:32'h3FFF_FFFF]};

RULE 4 \u2014 TRANSITION BINS FOR FSM STATES
If the RTL contains an FSM (State Machine) or sequential protocol phases:
You MUST create transition bins to verify the actual state changes:
  bins trans_idle_to_start = (IDLE => START);
  bins trans_start_to_data = (START => DATA);
Check the RTL FSM logic to determine the valid transitions.

RULE 5 \u2014 MEANINGFUL CROSS COVERAGE
Create cross coverage between signals that have logical relationships:
  - Valid and Opcode (all opcodes tested while valid is high)
  - Write_en and Full / Read_en and Empty (boundary conditions)
  - Control signals and their corresponding status flags
Only cross coverpoints that are present in THIS coverage component's actual
sequence item. In multi-agent mode, do not cross fields from different agent
item types unless the generated collector explicitly samples a common item.
Keep crosses to two coverpoints by default. Use ignore_bins/illegal_bins or
small, explicit bins to remove unreachable combinations; never create a
wide-bus or all-input Cartesian-product cross.

RULE 6 \u2014 COVERAGE COMPLETENESS CHECKLIST
Before submitting, verify that your code includes:
  [ ] A complete covergroup declaration with per_instance option
  [ ] Coverpoints for all 1-bit control signals (bins for 0 and 1)
  [ ] Coverpoints for multi-bit signals (using ranges if > 4 bits)
  [ ] Transition bins if the DUT has an FSM or protocol sequence
  [ ] Cross coverage for related signals

RULE 7 \u2014 SEQ_ITEM CONTAINS BOTH INPUTS AND OUTPUTS  \u26a0 CRITICAL \u26a0
The sequence_item that arrives at the coverage collector contains BOTH:
  INPUT fields:  the values the Driver sent TO the DUT this cycle.
  OUTPUT fields: the values the Monitor captured FROM the DUT this cycle.

This means you CAN and SHOULD write coverpoints for BOTH inputs and outputs.
  \u2713 CORRECT: cp_write_en: coverpoint sequence_item.write_en {...}   // input
  \u2713 CORRECT: cp_full:     coverpoint sequence_item.full {...}        // output flag
  \u2717 WRONG:   only writing coverpoints for inputs and ignoring output flags.

The OUTPUT fields are especially important for verifying that STATUS SIGNALS
(busy, full, empty, valid_out, done, overflow, etc.) were exercised in all states.

RULE 8 \u2014 NEVER WRITE A COVERPOINT FOR THE CLOCK SIGNAL  \u26a0 CRITICAL \u26a0
The clock is NOT a field in the sequence_item -- it is excluded by the tool.
  \u2717 WRONG: cp_clk: coverpoint sequence_item.clk {...}
  \u2713 RIGHT: skip the clock -- only cover functional signals.

RULE 9 \u2014 COVERAGE FEASIBILITY GATE
Before output, inspect every coverpoint and cross:
  [ ] Every referenced sequence_item field exists in the supplied skeleton.
  [ ] No transition bin names internal FSM states unless that state is an
      observable item field; otherwise cover observable state indicators.
  [ ] Wide values use a small, intentional set of bins.
  [ ] Each cross has a concrete verification purpose and bounded bin count.
"""

    # ── 5d. Random Constraints Critical Rules ─────────────────────────────────
    constraints_rules = ""
    if task_category == "random_constraints":
        constraints_rules = """
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
SECTION 5 \u2014 RANDOM CONSTRAINTS CRITICAL RULES  \u26a0 READ BEFORE WRITING \u26a0
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550

RULE 1 \u2014 INPUTS vs OUTPUTS [CRITICAL]
Look at the RTL ports in Section 3:
  - Every INPUT port must be declared as rand bit (or rand logic).
  - Every OUTPUT port must be declared as bit (or logic) WITHOUT the rand keyword.
  \u2717 WRONG: rand bit tx_out; (Outputs are driven by DUT, never randomized by Sequence).

RULE 2 \u2014 DEFAULT SOFT CONSTRAINTS (DANGER ZONE)
Provide a Global_Constraint block with soft constraints ONLY for central control signals:
  - soft reset_n == 1;  (Keep the DUT out of reset by default).
  - soft enable == 1;   (Keep the DUT active by default).
  \u26a0 NEVER put a soft constraint on Data Buses or Serial Protocol Inputs
     (like RX_IN, MOSI, SDA, data_in). Pinning these ruins coverage!

RULE 3 \u2014 IMPLICATION CONSTRAINTS (->)
Only if the RTL/protocol specification proves a combination is illegal, enforce it:
  - (valid == 0) -> (data == 0);
  - (read_en == 1) -> (write_en == 0);
Do not invent mutual exclusion merely because signals have familiar names;
some legal designs support simultaneous read/write or valid+ready operation.

RULE 4 \u2014 SOLVE BEFORE
If a probability skew is possible between dependent variables, use solve X before Y;:
  - solve valid before data; ensures the solver doesn't force valid=1 99.99% of the time.

RULE 5 \u2014 POST_RANDOMIZE FOR COMPUTED FIELDS
If the sequence item needs a parity bit, CRC, or calculated checksum, do NOT declare rand.
Calculate it inside function void post_randomize(); based on the randomized data.

RULE 6 \u2014 PROTOCOL CONTROL KNOBS (For Cycle-by-Cycle Drivers)
If the RTL is a serial protocol (UART, SPI, I2C) driven cycle-by-cycle, raw pins should
not be purely random. Add helper rand enum state variables (Knobs) to the sequence item
and constrain the physical pins to these knobs:
  rand enum {PROT_IDLE, PROT_START, PROT_DATA} cycle_state;
  constraint protocol_c { (cycle_state == PROT_IDLE) -> RX_IN == 1; }
This lets the Sequence orchestrate multi-cycle protocol packets.

RULE 7 \u2014 ONE RANDOMIZE = ONE CLOCK CYCLE  \u26a0 CRITICAL \u26a0
In this cycle-by-cycle tool, every call to randomize() = EXACTLY ONE clock cycle.
This has profound implications:

  (A) DO NOT think in "frames" or "packets" -- think in individual CYCLES.
      A UART frame of 11 bits needs 11 separate randomize() calls (11 seq_items).
      Each call must produce values valid for THAT SPECIFIC cycle type.

  (B) FOR PROTOCOL DUTs: The cycle_state Knob (RULE 6) is the ONLY mechanism
      for communicating "what type of cycle is this?" to the seq_item.
      The Sequence controls cycle_state. Your constraints respond to it.

  (C) FOR TIMING-SENSITIVE DUTs (baud-rate UART, SCK-divided SPI):
      The seq_item is NOT responsible for baud timing -- the Sequence handles that.
      Your constraints ensure each individual cycle's values are self-consistent.

  (D) SIGNAL HOLD PATTERN (signal must remain stable for N cycles):
      Add a rand bit keep_stable field with a high-probability-1 distribution:
        constraint Stability_c {
          keep_stable dist { 1'b1 := 90, 1'b0 := 10 };
        }
      When the Sequence needs to hold a signal stable, it sets keep_stable=1 and
      re-uses the same constraint value across consecutive randomize() calls.

RULE 8 \u2014 CONSTRAINT SOLVABILITY AND ESCAPE HATCH
Keep Global_Constraint permissive. Prefer soft constraints for defaults and
place scenario-specific restrictions only in the named sequence constraint.
Before output, verify by inspection that each implication, inside range, and
distribution can be satisfied together for every selector/knob value. Do not
add a new rand protocol knob unless the sequence can set it and its physical
pin mapping is derived from the actual protocol. Never constrain DUT output
fields. If a scenario needs an otherwise illegal raw-pin pattern, it must be
possible for the sequence to disable or override that scenario constraint.

  ✗ WRONG: modeling a whole UART frame (start+8bits+parity+stop) inside the seq_item.
  ✓ RIGHT: make each individual cycle valid on its own; let the Sequence orchestrate.
"""

        # ── 6. Construct Prompt ───────────────────────────────────────────────────
    task_display = task_category.replace('_', ' ').title()
    prompt = f"""You are an expert verification engineer skilled in SystemVerilog, UVM, C, and Python.

Your task: Complete the provided skeleton file for {task_display}.
{tool_architecture_section}
═══════════════════════════════════════════════════════════════════════════
SECTION 1 — STYLE & FORMAT REFERENCE
═══════════════════════════════════════════════════════════════════════════
Study these style patterns carefully. You MUST match this formatting exactly.
This section teaches you HOW to write the code.
NOTE: The snippets below use generic names (e.g. <DUT_name>, <signalA>, <control_signal>). You MUST replace these with the ACTUAL signal names from the Project Context in Section 2.

{style_section}

═══════════════════════════════════════════════════════════════════════════
SECTION 2 — PROJECT DESIGN CONTEXT  ⚠ READ THIS COMPLETELY BEFORE SECTION 3 ⚠
═══════════════════════════════════════════════════════════════════════════
These are the existing files in the project. Use them to understand the design,
signals, parameters, and interfaces. This section tells you WHAT to write about.
Read every file below in full before you look at the skeleton in Section 3.

IMPORTANT: The interface file below contains the clock signal name.
Use that EXACT name in all clock-sensitive code.

{context_section}

═══════════════════════════════════════════════════════════════════════════
SECTION 3 — TARGET FILE (fill this skeleton)
═══════════════════════════════════════════════════════════════════════════
The UVM generator tool has already created this skeleton file.
You must fill it with the actual {task_display} logic. Keep the exact module/class/function headers.
⚠ You must have read Section 2 (RTL context) completely before filling this skeleton.

`{code_fence}
{skeleton_content}
`

═══════════════════════════════════════════════════════════════════════════
SECTION 4 — USER INSTRUCTIONS
═══════════════════════════════════════════════════════════════════════════
{user_instructions}
{ref_model_rules}{assertions_rules}{coverage_rules}{constraints_rules}
═══════════════════════════════════════════════════════════════════════════
OUTPUT CONSTRAINT
═══════════════════════════════════════════════════════════════════════════
{output_constraint}
"""
    return prompt
